### ISSUE TITLE
Update Swagger to version 2.1.3

### ISSUE THREAD

**Issue by mjanser** [activelamp/swagger-ui-bundle#11]
Can you update at least to version 2.1.3 of Swagger? This would fix a bug for not sending multiple authentications.

I also tried 2.1.4 but it seems that it has a new dependency to a json editor.

**Comment by velovint** [comment]
Is there anything we can help to get it merged?

**Comment by Tobion** [comment]
This can be closed I assume.

**Comment by mjanser** [comment]
Yes, I'll close this.
